Refactored evaluation
JuliaTrustworthyAI/CounterfactualExplanations.jl pull request #227
Opened 2023-06-11 14:50 UTC by laurikskl

Refactored evaluation.

Sorted out exports and imports.

Also broke up the evaluate methods to several smaller functions to reduce CC and improve readability.

2023-06-12 11:26 UTC, kmariuszk requested changes

2023-06-12 11:26 UTC, kmariuszk commented on src/evaluation/Evaluation.jl
In your other PR (#229) you used the following order: `using`, `include`, `export` but here `export` and `include` are the other way around. Could you please change it so we'd end up using the same convention in all files?

2023-06-14 07:48 UTC, kmariuszk approved these changes

2023-06-14 09:56 UTC, VincentPikand requested changes
please go over everything again and add all namespace prefixes, I didn't comment on every single one I found.

2023-06-14 09:56 UTC, VincentPikand commented on src/evaluation/benchmark.jl
>      evaluation::DataFrame
`DataFrames.DataFrame`

2023-06-14 09:56 UTC, VincentPikand commented on src/evaluation/evaluate.jl
> +    evaluation = DataFrame(
no prefix on DataFrame

2023-06-14 09:56 UTC, VincentPikand commented on src/evaluation/evaluate.jl
> +        evaluation = stack(evaluation, Not(:num_counterfactual))
no prefix on `Not`

2023-06-14 09:56 UTC, VincentPikand commented on src/evaluation/evaluate.jl
> +    evaluation::DataFrame,
as mentioned above

2023-06-14 09:56 UTC, VincentPikand commented on src/evaluation/measures.jl
>      val = val isa AbstractMatrix ? vec(val) : val
`AbstractMatrix` not from `Base`

2023-06-16 14:57 UTC, laurikskl commented
> please go over everything again and add all namespace prefixes, I didn't comment on every single one I found.

done

2023-06-16 15:12 UTC, kmariuszk approved these changes

2023-06-16 15:54 UTC, VincentPikand approved these changes

2023-06-16 15:54 UTC, merged