212 refactor `models` folder
JuliaTrustworthyAI/CounterfactualExplanations.jl pull request #231
Opened 2023-06-12 12:33 UTC by VincentPikand

Closes #212

2023-06-12 13:09 UTC, kmariuszk requested changes
I have two questions about your decisions and thus some suggestions.

1. Why did you decide to keep the `utils` folder?
2. Since you created the `differentiable/flux` directory why you didn't create something similar for the `laplace_redux.jl` file? I had a similar discussion with Rauno about this categorization and maybe you can create another directory e.g., `differentiable/laplace_redux` or `differentiable/custom`? Thanks to that the `differentiable` folder would have a cleaner structure.

2023-06-12 13:11 UTC, VincentPikand commented on src/models/Models.jl
> +include("pretrained/pretrained.jl")
No, they are meant to be separated a bit

2023-06-12 13:15 UTC, VincentPikand commented
> I have two questions about your decisions and thus some suggestions.
> 
>     1. Why did you decide to keep the `utils` folder?
> 
>     2. Since you created the `differentiable/flux` directory why you didn't create something similar for the `laplace_redux.jl` file? I had a similar discussion with Rauno about this categorization and maybe you can create another directory e.g., `differentiable/laplace_redux` or `differentiable/custom`? Thanks to that the `differentiable` folder would have a cleaner structure.

1) I think you mean `utils.jl`, not `utils` folder. I decided to keep it because I couldn't think of a good way to separate those functions that would be meaningful and not completely arbitrary.
2) a `custom` folder is undescriptive and if more models are created, then a more relevant structuring can be created. For now, it can stay there.

2023-06-12 13:22 UTC, kmariuszk commented on src/models/Models.jl
> +include("pretrained/pretrained.jl")
Why? As far as I know, we're not doing this anywhere else and from a user perspective I always skip those `using` and `include` lines when I go through code. If I needed to find some specific bits of information about imports, I'd use `ctrl+f` anyway and having all necessary imports in one place seems to be convenient enough. 

Also, please leave it to a reviewer to decide whether a conversation is resolved.

2023-06-12 13:27 UTC, kmariuszk commented
> > I have two questions about your decisions and thus some suggestions.
> > ```
> > 1. Why did you decide to keep the `utils` folder?
> > 
> > 2. Since you created the `differentiable/flux` directory why you didn't create something similar for the `laplace_redux.jl` file? I had a similar discussion with Rauno about this categorization and maybe you can create another directory e.g., `differentiable/laplace_redux` or `differentiable/custom`? Thanks to that the `differentiable` folder would have a cleaner structure.
> > ```
> 
>     1. I think you mean `utils.jl`, not `utils` folder. I decided to keep it because I couldn't think of a good way to separate those functions that would be meaningful and not completely arbitrary.
> 
>     2. a `custom` folder is undescriptive and if more models are created, then a more relevant structuring can be created. For now, it can stay there.

Yes, I meant `utils.jl` and after going through this file once again it makes sense to leave it the way it is.

I'd still create one of those folders to keep this stuff separate, I'd argue that leaving a random `laplace_redux.jl` file could be even more confusing and creating one more folder wouldn't hurt.

2023-06-12 13:51 UTC, kmariuszk commented on src/models/Models.jl
> +include("pretrained/pretrained.jl")
May I ask for the link to the file from which you took a screenshot? 🙂

2023-06-12 14:13 UTC, kmariuszk commented on src/models/Models.jl
> +include("pretrained/pretrained.jl")
Great! I'm fully convinced your approach makes sense. Thank you for the clarification.

2023-06-13 09:30 UTC, RaunoArike approved these changes
Seems like a straightforward PR, didn't find any mistakes or questionable decisions. Approved.

2023-06-13 10:07 UTC, kmariuszk requested changes
Everything looks great except that `pure Flux` thingy. Please also add an informative description of this PR.

2023-06-13 10:07 UTC, kmariuszk commented on src/models/differentiable/differentiable.jl
> +Base type for differentiable models written in pure Flux.
`Pure Flux`? I think it's supposed to be just `Flux`.

2023-06-13 10:20 UTC, kmariuszk approved these changes

2023-06-13 10:20 UTC, merged