restructure files and improve imports
JuliaTrustworthyAI/CounterfactualExplanations.jl pull request #232
Opened 2023-06-13 10:25 UTC by VincentPikand

closes #211

2023-06-13 13:54 UTC, RaunoArike requested changes
I left one comment that I'd like to see resolved, otherwise the changes look fine.

2023-06-13 13:54 UTC, RaunoArike commented on src/generators/Generators.jl
> +include("non_gradient_based/feature_tweak/featuretweak.jl")
`feature_tweak/featuretweak.jl` is a bit weird naming - I think the file and the folder should have names formatted in the same way.

2023-06-13 13:57 UTC, A-Salmon reviewed
I was going to comment the same thing as Rauno, other than that I think it's good. Well done! I'll approve once this is addressed.

2023-06-13 16:13 UTC, RaunoArike approved these changes

2023-06-14 10:16 UTC, A-Salmon approved these changes

2023-06-14 10:18 UTC, merged